apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: simple-app-canary
  namespace: monitoring
  labels:
    release: prometheus
spec:
  podMetricsEndpoints:
    - path: /metrics
      port: "prometheus"
  selector:
    matchLabels:
      app: simple-app
  namespaceSelector:
    matchNames:
      - default
