apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: simple-app
        image: simple-app:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: simple-app
          containerPort: 8080
        - name: prometheus
          containerPort: 8000